#!/usr/bin/env python3
"""Emit preset_textures_data.h — the 10 preset layer PNGs as C byte arrays.

The DLL loads these via Textures_GetOrCreateFromMemory (no Windows resource
lookup, no module handle), which sidestepped a FindResource "resource not found"
failure with the .rc/RCDATA path. Regenerate after re-rasterizing the PNGs:

    cd cursor/assets && python3 gen_texture_data.py
"""
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
PRESETS = HERE / "presets"
OUT = HERE / "preset_textures_data.h"

# (C symbol, filename) — order/names must match kPresetTex in entry.cpp.
LAYERS = [
    ("kPulseRingOutline",       "pulse-ring-outline.png"),
    ("kPulseRingColour",        "pulse-ring-colour.png"),
    ("kCornerReticleOutline",   "corner-reticle-outline.png"),
    ("kCornerReticleColour",    "corner-reticle-colour.png"),
    ("kBeaconCrosshairOutline", "beacon-crosshair-outline.png"),
    ("kBeaconCrosshairColour",  "beacon-crosshair-colour.png"),
    ("kRadarDashOutline",       "radar-dash-outline.png"),
    ("kRadarDashColour",        "radar-dash-colour.png"),
    ("kSoftHaloOutline",        "soft-halo-outline.png"),
    ("kSoftHaloColour",         "soft-halo-colour.png"),
]


def emit_array(sym: str, data: bytes) -> str:
    body = []
    for i in range(0, len(data), 20):
        body.append("    " + ",".join(str(b) for b in data[i:i + 20]) + ",")
    return (f"inline const unsigned char {sym}[] = {{\n"
            + "\n".join(body)
            + f"\n}};\ninline const unsigned int {sym}_len = {len(data)}u;\n")


def main() -> None:
    parts = [
        "// GENERATED by gen_texture_data.py — do not edit by hand.",
        "// The five presets' outline/colour layer PNGs, embedded as byte arrays and",
        "// loaded via Textures_GetOrCreateFromMemory (see cursor/src/entry.cpp).",
        "#pragma once",
        "",
        "namespace cursor_art {",
        "",
    ]
    for sym, fname in LAYERS:
        data = (PRESETS / fname).read_bytes()
        parts.append(f"// {fname} ({len(data)} bytes)")
        parts.append(emit_array(sym, data))
    parts.append("} // namespace cursor_art")
    OUT.write_text("\n".join(parts) + "\n")
    total = sum((PRESETS / f).stat().st_size for _, f in LAYERS)
    print(f"wrote {OUT.name}: {len(LAYERS)} arrays, {total} bytes of PNG")


if __name__ == "__main__":
    main()
